name: cv1
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - argon2-cffi-bindings=21.2.0
  - async-lru=2.0.4
  - beautifulsoup4=4.12.3
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - certifi=2024.8.30
  - charset-normalizer=3.3.2
  - decorator=5.1.1
  - defusedxml=0.7.1
  - h11=0.14.0
  - ipython=8.27.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.2.5
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.27.3
  - libcxx=14.0.6
  - libexpat=2.6.2
  - libfaiss=1.9.0
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libopenblas=0.3.21
  - libsodium=1.0.18
  - libsqlite=3.46.1
  - libzlib=1.3.1
  - llvm-openmp=14.0.6
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nomkl=3.0
  - notebook=7.2.2
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openblas=0.3.21
  - openblas-devel=0.3.21
  - openssl=3.3.1
  - packaging=24.1
  - pip=24.2
  - prometheus_client=0.14.1
  - prompt_toolkit=3.0.43
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pysocks=1.7.1
  - python=3.12.4
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - pytz=2024.1
  - readline=8.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - setuptools=73.0.1
  - six=1.16.0
  - stack_data=0.2.0
  - tk=8.6.13
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.11.0
  - urllib3=2.2.2
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.44.0
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - pip:
      - absl-py==2.1.0
      - anyio==4.4.0
      - appnope==0.1.4
      - argon2-cffi==23.1.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - attrs==24.2.0
      - av==13.0.0
      - babel==2.16.0
      - bleach==6.1.0
      - cffi==1.17.0
      - clip==1.0
      - comm==0.2.2
      - contourpy==1.3.0
      - cycler==0.12.1
      - debugpy==1.8.5
      - et-xmlfile==1.1.0
      - executing==2.1.0
      - faiss-cpu==1.8.0.post1
      - fastjsonschema==2.20.0
      - filelock==3.15.4
      - fonttools==4.53.1
      - fqdn==1.5.1
      - fsspec==2024.6.1
      - ftfy==6.3.0
      - grpcio==1.66.1
      - httpcore==1.0.5
      - httpx==0.27.2
      - idna==3.8
      - imageio==2.35.1
      - ipykernel==6.29.5
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - joblib==1.4.2
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter==1.1.0
      - jupyter-client==8.6.2
      - jupyter-console==6.6.3
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab-pygments==0.3.0
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.6
      - lazy-loader==0.4
      - markdown==3.7
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - mistune==3.0.2
      - mpmath==1.3.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - networkx==3.3
      - notebook-shim==0.2.4
      - opencv-contrib-python==4.10.0.84
      - opencv-python==4.10.0.84
      - openpyxl==3.1.5
      - overrides==7.7.0
      - pandas==2.2.2
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==10.4.0
      - platformdirs==4.2.2
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.47
      - protobuf==5.28.0
      - psutil==6.0.0
      - pure-eval==0.2.3
      - pycparser==2.22
      - pygments==2.18.0
      - pyparsing==3.1.4
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - referencing==0.35.1
      - regex==2024.9.11
      - rpds-py==0.20.0
      - scikit-image==0.24.0
      - scikit-learn==1.5.1
      - scipy==1.14.1
      - send2trash==1.8.3
      - sniffio==1.3.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - sympy==1.13.2
      - tensorboard==2.17.1
      - tensorboard-data-server==0.7.2
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tifffile==2024.9.20
      - tinycss2==1.3.0
      - torch==2.4.0
      - torchinfo==1.8.0
      - torchvision==0.19.0
      - tqdm==4.66.5
      - types-python-dateutil==2.9.0.20240821
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - uri-template==1.3.0
      - wcwidth==0.2.13
      - webcolors==24.8.0
      - werkzeug==3.0.4
      - widgetsnbextension==4.0.13
