name: cv1_final2
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - attrs=24.2.0
  - babel=2.14.0
  - beautifulsoup4=4.12.3
  - bleach=6.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - comm=0.2.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - fqdn=1.5.1
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.0.0
  - httpcore=1.0.6
  - httpx=0.27.2
  - hyperframe=6.0.1
  - idna=3.10
  - importlib-metadata=8.5.0
  - importlib_metadata=8.5.0
  - importlib_resources=6.4.5
  - ipykernel=6.29.5
  - ipython=8.27.0
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - json5=0.9.25
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.2.5
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.27.3
  - libcxx=14.0.6
  - libexpat=2.6.2
  - libffi=3.4.2
  - libsodium=1.0.18
  - libsqlite=3.46.1
  - libzlib=1.3.1
  - markupsafe=3.0.1
  - matplotlib-inline=0.1.7
  - mistune=3.0.2
  - nbclient=0.10.0
  - nbconvert-core=7.16.4
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - notebook=7.2.2
  - notebook-shim=0.2.4
  - openssl=3.3.1
  - overrides=7.7.0
  - packaging=24.1
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=6.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.22
  - pygments=2.18.0
  - pyobjc-core=10.3.1
  - pyobjc-framework-cocoa=10.3.1
  - pysocks=1.7.1
  - python=3.12.4
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python_abi=3.12
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=25.1.1
  - readline=8.2
  - referencing=0.35.1
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.20.0
  - send2trash=1.8.3
  - setuptools=73.0.1
  - six=1.16.0
  - sniffio=1.3.1
  - soupsieve=2.5
  - stack_data=0.2.0
  - terminado=0.18.1
  - tinycss2=1.3.0
  - tk=8.6.13
  - tomli=2.0.2
  - tornado=6.4.1
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20241003
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - typing_utils=0.1.0
  - tzdata=2024b
  - uri-template=1.3.0
  - urllib3=2.2.2
  - wcwidth=0.2.13
  - webcolors=24.8.0
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.44.0
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.20.2
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - anyio==4.4.0
      - clip==1.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - faiss-cpu==1.8.0.post1
      - filelock==3.16.1
      - fonttools==4.54.1
      - fsspec==2024.9.0
      - ftfy==6.2.3
      - imageio==2.35.1
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - matplotlib==3.9.2
      - mpmath==1.3.0
      - networkx==3.3
      - numpy==1.26.4
      - opencv-contrib-python==4.10.0.84
      - opencv-python==4.10.0.84
      - pillow==10.4.0
      - pyparsing==3.1.4
      - regex==2024.9.11
      - scikit-image==0.24.0
      - scikit-learn==1.5.1
      - scipy==1.14.1
      - sympy==1.13.3
      - threadpoolctl==3.5.0
      - tifffile==2024.9.20
      - torch==2.2.0
      - torchinfo==1.8.0
      - torchvision==0.17.0
      - tqdm==4.66.5
